services:
  - type: web
    name: cookingrecipes-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
